author: "DINH KHAC QUY"
description: "PROFILE DINH KHAC QUY"
permalink: /:title/
encoding: utf-8
base_url:
    En: /
    Vi: /vi/Introduction/
    Fr: /fr/Introduction/

t:
    title:
        English: "PROFILE DINH KHAC QUY"
        Vitnamese: "HỒ SƠ ĐINH KHẮC QUÝ"        
        French: "PROFILE DINH KHAC QUY"

# exclude_from_localizations: ["assets", "CNAME"]
# exclude_from_localizations: ["javascript", "images", "css", "xml"]

show_footer: false           # show the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark 
dark_footer: false           # keep the footer dark
#style: minimal             # use a simpler style inspired by the minima theme
  

#icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github: "https://github.com/niklasbuschmann/contrast"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
