defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Christian Ezeani
subtitle: Full-Stack Developer

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
